"""localization

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 14:05:05.154464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localization_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_localization_keys')),
    sa.UniqueConstraint('key', name=op.f('uq_localization_keys_key'))
    )
    op.create_index(op.f('ix_localization_keys_namespace'), 'localization_keys', ['namespace'], unique=False)
    op.create_table('localization_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("locale IN ('en','tr','zh-CN','es')", name=op.f('ck_localization_values_locale_supported')),
    sa.CheckConstraint("status IN ('missing','draft','reviewed','published')", name=op.f('ck_localization_values_status_valid')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_localization_values_version_positive')),
    sa.ForeignKeyConstraint(['key_id'], ['localization_keys.id'], name=op.f('fk_localization_values_key_id_localization_keys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_localization_values')),
    sa.UniqueConstraint('key_id', 'locale', name=op.f('uq_localization_values_key_id_locale'))
    )
    op.create_index('ix_localization_values_locale_status', 'localization_values', ['locale', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_localization_values_locale_status', table_name='localization_values')
    op.drop_table('localization_values')
    op.drop_index(op.f('ix_localization_keys_namespace'), table_name='localization_keys')
    op.drop_table('localization_keys')
    # ### end Alembic commands ###
