"""progression wallets ledger

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30 17:17:38.014250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_stat_allocations',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('str_points', sa.Integer(), nullable=False),
    sa.Column('dex_points', sa.Integer(), nullable=False),
    sa.Column('int_points', sa.Integer(), nullable=False),
    sa.Column('vit_points', sa.Integer(), nullable=False),
    sa.Column('wis_points', sa.Integer(), nullable=False),
    sa.Column('spi_points', sa.Integer(), nullable=False),
    sa.Column('luk_points', sa.Integer(), nullable=False),
    sa.Column('last_respec_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dex_points >= 0', name=op.f('ck_character_stat_allocations_dex_non_negative')),
    sa.CheckConstraint('int_points >= 0', name=op.f('ck_character_stat_allocations_int_non_negative')),
    sa.CheckConstraint('luk_points >= 0', name=op.f('ck_character_stat_allocations_luk_non_negative')),
    sa.CheckConstraint('spi_points >= 0', name=op.f('ck_character_stat_allocations_spi_non_negative')),
    sa.CheckConstraint('str_points >= 0', name=op.f('ck_character_stat_allocations_str_non_negative')),
    sa.CheckConstraint('vit_points >= 0', name=op.f('ck_character_stat_allocations_vit_non_negative')),
    sa.CheckConstraint('wis_points >= 0', name=op.f('ck_character_stat_allocations_wis_non_negative')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_stat_allocations_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk_character_stat_allocations'))
    )
    op.create_table('economy_ledger',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('delta', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('ref_type', sa.String(length=48), nullable=True),
    sa.Column('ref_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_after >= 0', name=op.f('ck_economy_ledger_balance_non_negative')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_economy_ledger_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_economy_ledger')),
    sa.UniqueConstraint('character_id', 'currency', 'idempotency_key', name=op.f('uq_economy_ledger_character_id_currency_idempotency_key'))
    )
    op.create_index('ix_economy_ledger_character_created', 'economy_ledger', ['character_id', 'created_at'], unique=False)
    op.create_index('ix_economy_ledger_reason_created', 'economy_ledger', ['reason', 'created_at'], unique=False)
    op.create_table('progression_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=48), nullable=True),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('level_before', sa.Integer(), nullable=False),
    sa.Column('level_after', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_progression_events_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progression_events')),
    sa.UniqueConstraint('character_id', 'idempotency_key', name=op.f('uq_progression_events_character_id_idempotency_key'))
    )
    op.create_index('ix_progression_events_character_created', 'progression_events', ['character_id', 'created_at'], unique=False)
    op.create_table('wallets',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('gold', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gold >= 0', name=op.f('ck_wallets_gold_non_negative')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_wallets_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk_wallets'))
    )
    op.add_column('characters', sa.Column('mastery_xp', sa.BigInteger(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'mastery_xp')
    op.drop_table('wallets')
    op.drop_index('ix_progression_events_character_created', table_name='progression_events')
    op.drop_table('progression_events')
    op.drop_index('ix_economy_ledger_reason_created', table_name='economy_ledger')
    op.drop_index('ix_economy_ledger_character_created', table_name='economy_ledger')
    op.drop_table('economy_ledger')
    op.drop_table('character_stat_allocations')
    # ### end Alembic commands ###
