"""races

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-30 17:25:20.133094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('identity', sa.String(length=32), nullable=False),
    sa.Column('trait_name_key', sa.String(length=200), nullable=False),
    sa.Column('trait_description_key', sa.String(length=200), nullable=False),
    sa.Column('title_key', sa.String(length=200), nullable=False),
    sa.Column('affinity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_races_status_valid')),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_races_sort_order_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_races_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_races_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_races')),
    sa.UniqueConstraint('code', name=op.f('uq_races_code'))
    )
    op.create_index(op.f('ix_races_status'), 'races', ['status'], unique=False)
    op.create_index(op.f('ix_characters_race_id'), 'characters', ['race_id'], unique=False)
    op.create_foreign_key(op.f('fk_characters_race_id_races'), 'characters', 'races', ['race_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_characters_race_id_races'), 'characters', type_='foreignkey')
    op.drop_index(op.f('ix_characters_race_id'), table_name='characters')
    op.drop_index(op.f('ix_races_status'), table_name='races')
    op.drop_table('races')
    # ### end Alembic commands ###
