"""classes

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-30 17:39:16.764459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armor_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_armor_families_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_armor_families_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_armor_families_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_armor_families')),
    sa.UniqueConstraint('code', name=op.f('uq_armor_families_code'))
    )
    op.create_index(op.f('ix_armor_families_status'), 'armor_families', ['status'], unique=False)
    op.create_table('base_classes',
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('role_key', sa.String(length=200), nullable=False),
    sa.Column('primary_stat', sa.String(length=3), nullable=False),
    sa.Column('secondary_stat', sa.String(length=3), nullable=False),
    sa.Column('utility_stat', sa.String(length=3), nullable=False),
    sa.Column('main_damage_stat', sa.String(length=3), nullable=False),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weapon_families', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('armor_families', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dual_wield', sa.Boolean(), nullable=False),
    sa.Column('item_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('base_passive_code', sa.String(length=96), nullable=False),
    sa.Column('base_effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('solo_accord', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('combat','support')", name=op.f('ck_base_classes_category_valid')),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_base_classes_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_base_classes_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_base_classes_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_base_classes')),
    sa.UniqueConstraint('code', name=op.f('uq_base_classes_code'))
    )
    op.create_index(op.f('ix_base_classes_status'), 'base_classes', ['status'], unique=False)
    op.create_table('class_resources',
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('start_value', sa.Float(), nullable=False),
    sa.Column('regen_per_s', sa.Float(), nullable=False),
    sa.Column('decay_per_s', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_class_resources_status_valid')),
    sa.CheckConstraint('max_value > 0', name=op.f('ck_class_resources_max_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_class_resources_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_class_resources_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_resources')),
    sa.UniqueConstraint('code', name=op.f('uq_class_resources_code'))
    )
    op.create_index(op.f('ix_class_resources_status'), 'class_resources', ['status'], unique=False)
    op.create_table('weapon_families',
    sa.Column('hands', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_weapon_families_status_valid')),
    sa.CheckConstraint('hands IN (1, 2)', name=op.f('ck_weapon_families_hands_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_weapon_families_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_weapon_families_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weapon_families')),
    sa.UniqueConstraint('code', name=op.f('uq_weapon_families_code'))
    )
    op.create_index(op.f('ix_weapon_families_status'), 'weapon_families', ['status'], unique=False)
    op.create_table('class_branches',
    sa.Column('base_class_code', sa.String(length=96), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('role_key', sa.String(length=200), nullable=False),
    sa.Column('passive_code', sa.String(length=96), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_class_branches_status_valid')),
    sa.ForeignKeyConstraint(['base_class_code'], ['base_classes.code'], name=op.f('fk_class_branches_base_class_code_base_classes'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_class_branches_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_class_branches_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_branches')),
    sa.UniqueConstraint('code', name=op.f('uq_class_branches_code'))
    )
    op.create_index(op.f('ix_class_branches_base_class_code'), 'class_branches', ['base_class_code'], unique=False)
    op.create_index(op.f('ix_class_branches_status'), 'class_branches', ['status'], unique=False)
    op.create_table('class_progression_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('base_class_code', sa.String(length=96), nullable=True),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('required_quest_code', sa.String(length=96), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('promotion','specialization','awakening','capstone','mastery')", name=op.f('ck_class_progression_requirements_stage_valid')),
    sa.CheckConstraint('min_level BETWEEN 1 AND 1000', name=op.f('ck_class_progression_requirements_level_valid')),
    sa.ForeignKeyConstraint(['base_class_code'], ['base_classes.code'], name=op.f('fk_class_progression_requirements_base_class_code_base_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_progression_requirements')),
    sa.UniqueConstraint('stage', 'base_class_code', name=op.f('uq_class_progression_requirements_stage_base_class_code'), postgresql_nulls_not_distinct=True)
    )
    op.create_table('specializations',
    sa.Column('branch_code', sa.String(length=96), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('role_key', sa.String(length=200), nullable=False),
    sa.Column('mastery_noun_key', sa.String(length=200), nullable=False),
    sa.Column('passive_code', sa.String(length=96), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_specializations_status_valid')),
    sa.ForeignKeyConstraint(['branch_code'], ['class_branches.code'], name=op.f('fk_specializations_branch_code_class_branches'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_specializations_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_specializations_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specializations')),
    sa.UniqueConstraint('code', name=op.f('uq_specializations_code'))
    )
    op.create_index(op.f('ix_specializations_branch_code'), 'specializations', ['branch_code'], unique=False)
    op.create_index(op.f('ix_specializations_status'), 'specializations', ['status'], unique=False)
    op.create_table('character_class_progressions',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('base_class_code', sa.String(length=96), nullable=False),
    sa.Column('branch_code', sa.String(length=96), nullable=True),
    sa.Column('specialization_code', sa.String(length=96), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('specialized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('awakened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capstone_unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mastery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('path_changes', sa.Integer(), nullable=False),
    sa.Column('last_path_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_class_code'], ['base_classes.code'], name=op.f('fk_character_class_progressions_base_class_code_base_classes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['branch_code'], ['class_branches.code'], name=op.f('fk_character_class_progressions_branch_code_class_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_class_progressions_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialization_code'], ['specializations.code'], name=op.f('fk_character_class_progressions_specialization_code_specializations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk_character_class_progressions'))
    )
    op.create_index(op.f('ix_characters_base_class_id'), 'characters', ['base_class_id'], unique=False)
    op.create_foreign_key(op.f('fk_characters_base_class_id_base_classes'), 'characters', 'base_classes', ['base_class_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_characters_base_class_id_base_classes'), 'characters', type_='foreignkey')
    op.drop_index(op.f('ix_characters_base_class_id'), table_name='characters')
    op.drop_table('character_class_progressions')
    op.drop_index(op.f('ix_specializations_status'), table_name='specializations')
    op.drop_index(op.f('ix_specializations_branch_code'), table_name='specializations')
    op.drop_table('specializations')
    op.drop_table('class_progression_requirements')
    op.drop_index(op.f('ix_class_branches_status'), table_name='class_branches')
    op.drop_index(op.f('ix_class_branches_base_class_code'), table_name='class_branches')
    op.drop_table('class_branches')
    op.drop_index(op.f('ix_weapon_families_status'), table_name='weapon_families')
    op.drop_table('weapon_families')
    op.drop_index(op.f('ix_class_resources_status'), table_name='class_resources')
    op.drop_table('class_resources')
    op.drop_index(op.f('ix_base_classes_status'), table_name='base_classes')
    op.drop_table('base_classes')
    op.drop_index(op.f('ix_armor_families_status'), table_name='armor_families')
    op.drop_table('armor_families')
    # ### end Alembic commands ###
