"""abilities talents awakening mastery

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-30 17:57:44.463784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability_definitions',
    sa.Column('owner_type', sa.String(length=16), nullable=False),
    sa.Column('owner_code', sa.String(length=96), nullable=True),
    sa.Column('ability_type', sa.String(length=16), nullable=False),
    sa.Column('unlock_level', sa.Integer(), nullable=False),
    sa.Column('target_rule', sa.String(length=24), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ranks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ability_type IN ('ACTIVE','PASSIVE','ULTIMATE','STANCE','AURA','PROC')", name=op.f('ck_ability_definitions_type_valid')),
    sa.CheckConstraint("owner_type IN ('class','branch','specialization','global')", name=op.f('ck_ability_definitions_owner_valid')),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_ability_definitions_status_valid')),
    sa.CheckConstraint('unlock_level BETWEEN 1 AND 1000', name=op.f('ck_ability_definitions_unlock_level_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ability_definitions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_ability_definitions_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ability_definitions')),
    sa.UniqueConstraint('code', name=op.f('uq_ability_definitions_code'))
    )
    op.create_index(op.f('ix_ability_definitions_owner_code'), 'ability_definitions', ['owner_code'], unique=False)
    op.create_index(op.f('ix_ability_definitions_status'), 'ability_definitions', ['status'], unique=False)
    op.create_table('mastery_definitions',
    sa.Column('base_class_code', sa.String(length=96), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('cosmetic_code', sa.String(length=96), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_mastery_definitions_status_valid')),
    sa.ForeignKeyConstraint(['base_class_code'], ['base_classes.code'], name=op.f('fk_mastery_definitions_base_class_code_base_classes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_mastery_definitions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_mastery_definitions_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mastery_definitions')),
    sa.UniqueConstraint('base_class_code', name=op.f('uq_mastery_definitions_base_class_code')),
    sa.UniqueConstraint('code', name=op.f('uq_mastery_definitions_code'))
    )
    op.create_index(op.f('ix_mastery_definitions_status'), 'mastery_definitions', ['status'], unique=False)
    op.create_table('talent_trees',
    sa.Column('base_class_code', sa.String(length=96), nullable=False),
    sa.Column('focus_key', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_talent_trees_status_valid')),
    sa.ForeignKeyConstraint(['base_class_code'], ['base_classes.code'], name=op.f('fk_talent_trees_base_class_code_base_classes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_talent_trees_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_talent_trees_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_talent_trees')),
    sa.UniqueConstraint('code', name=op.f('uq_talent_trees_code'))
    )
    op.create_index(op.f('ix_talent_trees_base_class_code'), 'talent_trees', ['base_class_code'], unique=False)
    op.create_index(op.f('ix_talent_trees_status'), 'talent_trees', ['status'], unique=False)
    op.create_table('talent_nodes',
    sa.Column('tree_code', sa.String(length=96), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('max_rank', sa.Integer(), nullable=False),
    sa.Column('required_points_in_tree', sa.Integer(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('is_capstone', sa.Boolean(), nullable=False),
    sa.Column('requires', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('archetype_key', sa.String(length=200), nullable=True),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_talent_nodes_status_valid')),
    sa.CheckConstraint('max_rank BETWEEN 1 AND 10', name=op.f('ck_talent_nodes_max_rank_valid')),
    sa.CheckConstraint('tier BETWEEN 1 AND 6', name=op.f('ck_talent_nodes_tier_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_talent_nodes_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tree_code'], ['talent_trees.code'], name=op.f('fk_talent_nodes_tree_code_talent_trees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_talent_nodes_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_talent_nodes')),
    sa.UniqueConstraint('code', name=op.f('uq_talent_nodes_code'))
    )
    op.create_index(op.f('ix_talent_nodes_status'), 'talent_nodes', ['status'], unique=False)
    op.create_index(op.f('ix_talent_nodes_tree_code'), 'talent_nodes', ['tree_code'], unique=False)
    op.create_table('awakening_definitions',
    sa.Column('specialization_code', sa.String(length=96), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_awakening_definitions_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_awakening_definitions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['specialization_code'], ['specializations.code'], name=op.f('fk_awakening_definitions_specialization_code_specializations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_awakening_definitions_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_awakening_definitions')),
    sa.UniqueConstraint('code', name=op.f('uq_awakening_definitions_code')),
    sa.UniqueConstraint('specialization_code', name=op.f('uq_awakening_definitions_specialization_code'))
    )
    op.create_index(op.f('ix_awakening_definitions_status'), 'awakening_definitions', ['status'], unique=False)
    op.create_table('character_talent_allocations',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('node_code', sa.String(length=96), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rank >= 1', name=op.f('ck_character_talent_allocations_rank_positive')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_talent_allocations_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_code'], ['talent_nodes.code'], name=op.f('fk_character_talent_allocations_node_code_talent_nodes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('character_id', 'node_code', name=op.f('pk_character_talent_allocations'))
    )
    op.add_column('character_class_progressions', sa.Column('talent_resets', sa.Integer(), server_default='0', nullable=False))
    op.add_column('character_class_progressions', sa.Column('talent_points_spent', sa.Integer(), server_default='0', nullable=False))
    op.add_column('character_class_progressions', sa.Column('last_talent_reset_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_class_progressions', 'last_talent_reset_at')
    op.drop_column('character_class_progressions', 'talent_points_spent')
    op.drop_column('character_class_progressions', 'talent_resets')
    op.drop_table('character_talent_allocations')
    op.drop_index(op.f('ix_awakening_definitions_status'), table_name='awakening_definitions')
    op.drop_table('awakening_definitions')
    op.drop_index(op.f('ix_talent_nodes_tree_code'), table_name='talent_nodes')
    op.drop_index(op.f('ix_talent_nodes_status'), table_name='talent_nodes')
    op.drop_table('talent_nodes')
    op.drop_index(op.f('ix_talent_trees_status'), table_name='talent_trees')
    op.drop_index(op.f('ix_talent_trees_base_class_code'), table_name='talent_trees')
    op.drop_table('talent_trees')
    op.drop_index(op.f('ix_mastery_definitions_status'), table_name='mastery_definitions')
    op.drop_table('mastery_definitions')
    op.drop_index(op.f('ix_ability_definitions_status'), table_name='ability_definitions')
    op.drop_index(op.f('ix_ability_definitions_owner_code'), table_name='ability_definitions')
    op.drop_table('ability_definitions')
    # ### end Alembic commands ###
