"""passive and afk profiles

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-30 18:24:17.174852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passive_profiles',
    sa.Column('base_class_code', sa.String(length=96), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_passive_profiles_status_valid')),
    sa.ForeignKeyConstraint(['base_class_code'], ['base_classes.code'], name=op.f('fk_passive_profiles_base_class_code_base_classes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_passive_profiles_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_passive_profiles_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passive_profiles')),
    sa.UniqueConstraint('code', name=op.f('uq_passive_profiles_code'))
    )
    op.create_index(op.f('ix_passive_profiles_base_class_code'), 'passive_profiles', ['base_class_code'], unique=False)
    op.create_index(op.f('ix_passive_profiles_status'), 'passive_profiles', ['status'], unique=False)
    op.create_table('character_afk_profiles',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('preset_code', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('stance', sa.String(length=32), nullable=False),
    sa.Column('target_priority', sa.String(length=16), nullable=False),
    sa.Column('potion_threshold_pct', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('passive_profile_code', sa.String(length=96), nullable=True),
    sa.Column('loot_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tactics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('PASSIVE_ONLY','ACTIVE_TACTICS','HYBRID')", name=op.f('ck_character_afk_profiles_mode_valid')),
    sa.CheckConstraint("risk_level IN ('safe','balanced','dangerous','elite_hunt')", name=op.f('ck_character_afk_profiles_risk_valid')),
    sa.CheckConstraint('potion_threshold_pct BETWEEN 0 AND 100', name=op.f('ck_character_afk_profiles_potion_threshold_valid')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_afk_profiles_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passive_profile_code'], ['passive_profiles.code'], name=op.f('fk_character_afk_profiles_passive_profile_code_passive_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk_character_afk_profiles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_afk_profiles')
    op.drop_index(op.f('ix_passive_profiles_status'), table_name='passive_profiles')
    op.drop_index(op.f('ix_passive_profiles_base_class_code'), table_name='passive_profiles')
    op.drop_table('passive_profiles')
    # ### end Alembic commands ###
