"""world zones enemies drops

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-30 21:55:48.290685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, Sequence[str], None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drop_tables',
    sa.Column('rolls', sa.Integer(), nullable=False),
    sa.Column('entries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_drop_tables_status_valid')),
    sa.CheckConstraint('rolls BETWEEN 0 AND 20', name=op.f('ck_drop_tables_rolls_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_drop_tables_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_drop_tables_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drop_tables')),
    sa.UniqueConstraint('code', name=op.f('uq_drop_tables_code'))
    )
    op.create_index(op.f('ix_drop_tables_status'), 'drop_tables', ['status'], unique=False)
    op.create_table('encounter_templates',
    sa.Column('members', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_encounter_templates_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_encounter_templates_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_encounter_templates_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounter_templates')),
    sa.UniqueConstraint('code', name=op.f('uq_encounter_templates_code'))
    )
    op.create_index(op.f('ix_encounter_templates_status'), 'encounter_templates', ['status'], unique=False)
    op.create_table('enemy_ability_profiles',
    sa.Column('abilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_enemy_ability_profiles_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_enemy_ability_profiles_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_enemy_ability_profiles_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enemy_ability_profiles')),
    sa.UniqueConstraint('code', name=op.f('uq_enemy_ability_profiles_code'))
    )
    op.create_index(op.f('ix_enemy_ability_profiles_status'), 'enemy_ability_profiles', ['status'], unique=False)
    op.create_table('zone_tiers',
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('scaling', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rarity_band', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_zone_tiers_status_valid')),
    sa.CheckConstraint('min_level >= 1 AND max_level <= 1000 AND min_level <= max_level', name=op.f('ck_zone_tiers_levels_valid')),
    sa.CheckConstraint('tier BETWEEN 0 AND 10', name=op.f('ck_zone_tiers_tier_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_zone_tiers_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_zone_tiers_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zone_tiers')),
    sa.UniqueConstraint('code', name=op.f('uq_zone_tiers_code')),
    sa.UniqueConstraint('tier', name=op.f('uq_zone_tiers_tier'))
    )
    op.create_index(op.f('ix_zone_tiers_status'), 'zone_tiers', ['status'], unique=False)
    op.create_table('boss_templates',
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('archetype', sa.String(length=32), nullable=False),
    sa.Column('damage_type', sa.String(length=16), nullable=False),
    sa.Column('stat_mods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ability_profile_code', sa.String(length=96), nullable=True),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('phases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('adds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enrage_after_s', sa.Float(), nullable=True),
    sa.Column('drop_table_code', sa.String(length=96), nullable=True),
    sa.Column('reward_pct', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_boss_templates_status_valid')),
    sa.ForeignKeyConstraint(['ability_profile_code'], ['enemy_ability_profiles.code'], name=op.f('fk_boss_templates_ability_profile_code_enemy_ability_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_boss_templates_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['drop_table_code'], ['drop_tables.code'], name=op.f('fk_boss_templates_drop_table_code_drop_tables'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_boss_templates_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boss_templates')),
    sa.UniqueConstraint('code', name=op.f('uq_boss_templates_code'))
    )
    op.create_index(op.f('ix_boss_templates_status'), 'boss_templates', ['status'], unique=False)
    op.create_table('enemy_templates',
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('archetype', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.String(length=16), nullable=False),
    sa.Column('damage_type', sa.String(length=16), nullable=False),
    sa.Column('stat_mods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ability_profile_code', sa.String(length=96), nullable=True),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reward_pct', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rank IN ('normal','elite')", name=op.f('ck_enemy_templates_rank_valid')),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_enemy_templates_status_valid')),
    sa.ForeignKeyConstraint(['ability_profile_code'], ['enemy_ability_profiles.code'], name=op.f('fk_enemy_templates_ability_profile_code_enemy_ability_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_enemy_templates_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_enemy_templates_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enemy_templates')),
    sa.UniqueConstraint('code', name=op.f('uq_enemy_templates_code'))
    )
    op.create_index(op.f('ix_enemy_templates_family'), 'enemy_templates', ['family'], unique=False)
    op.create_index(op.f('ix_enemy_templates_status'), 'enemy_templates', ['status'], unique=False)
    op.create_table('zones',
    sa.Column('tier_code', sa.String(length=96), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('recommended_level', sa.Integer(), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('danger_rating', sa.Integer(), nullable=False),
    sa.Column('environment_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('encounter_pool', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('boss_pool', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('boss_chance_pct', sa.Float(), nullable=False),
    sa.Column('loot_modifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('drop_table_code', sa.String(length=96), nullable=True),
    sa.Column('profession_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_zones_status_valid')),
    sa.CheckConstraint('boss_chance_pct BETWEEN 0 AND 100', name=op.f('ck_zones_boss_chance_valid')),
    sa.CheckConstraint('danger_rating BETWEEN 1 AND 10', name=op.f('ck_zones_danger_valid')),
    sa.CheckConstraint('min_level >= 1 AND min_level <= recommended_level AND recommended_level <= max_level AND max_level <= 1000', name=op.f('ck_zones_levels_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_zones_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['drop_table_code'], ['drop_tables.code'], name=op.f('fk_zones_drop_table_code_drop_tables'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tier_code'], ['zone_tiers.code'], name=op.f('fk_zones_tier_code_zone_tiers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_zones_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones')),
    sa.UniqueConstraint('code', name=op.f('uq_zones_code'))
    )
    op.create_index(op.f('ix_zones_min_level'), 'zones', ['min_level'], unique=False)
    op.create_index(op.f('ix_zones_status'), 'zones', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zones_status'), table_name='zones')
    op.drop_index(op.f('ix_zones_min_level'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_enemy_templates_status'), table_name='enemy_templates')
    op.drop_index(op.f('ix_enemy_templates_family'), table_name='enemy_templates')
    op.drop_table('enemy_templates')
    op.drop_index(op.f('ix_boss_templates_status'), table_name='boss_templates')
    op.drop_table('boss_templates')
    op.drop_index(op.f('ix_zone_tiers_status'), table_name='zone_tiers')
    op.drop_table('zone_tiers')
    op.drop_index(op.f('ix_enemy_ability_profiles_status'), table_name='enemy_ability_profiles')
    op.drop_table('enemy_ability_profiles')
    op.drop_index(op.f('ix_encounter_templates_status'), table_name='encounter_templates')
    op.drop_table('encounter_templates')
    op.drop_index(op.f('ix_drop_tables_status'), table_name='drop_tables')
    op.drop_table('drop_tables')
    # ### end Alembic commands ###
