"""afk sessions

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-30 22:13:50.294999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, Sequence[str], None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afk_daily_usage',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.CheckConstraint('seconds >= 0', name=op.f('ck_afk_daily_usage_seconds_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_afk_daily_usage_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day', name=op.f('pk_afk_daily_usage'))
    )
    op.create_table('afk_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('zone_code', sa.String(length=96), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('start_idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_hash', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('claim_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ends_at <= started_at + interval '3 hours'", name=op.f('ck_afk_sessions_max_three_hours')),
    sa.CheckConstraint("status IN ('running','resolved','claimed','cancelled')", name=op.f('ck_afk_sessions_status_valid')),
    sa.CheckConstraint('ends_at > started_at', name=op.f('ck_afk_sessions_ends_after_start')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_afk_sessions_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_afk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afk_sessions'))
    )
    op.create_index('ix_afk_sessions_character_created', 'afk_sessions', ['character_id', 'created_at'], unique=False)
    op.create_index('ix_afk_sessions_sweep', 'afk_sessions', ['status', 'ends_at'], unique=False)
    op.create_index(op.f('ix_afk_sessions_user_id'), 'afk_sessions', ['user_id'], unique=False)
    op.create_index('uq_afk_sessions_one_active', 'afk_sessions', ['character_id'], unique=True, postgresql_where=sa.text("status IN ('running','resolved')"))
    op.create_table('character_afk_stats',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('pity_counter', sa.Integer(), nullable=False),
    sa.Column('sessions_claimed', sa.Integer(), nullable=False),
    sa.Column('total_seconds', sa.BigInteger(), nullable=False),
    sa.Column('last_claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_afk_stats_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk_character_afk_stats'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_afk_stats')
    op.drop_index('uq_afk_sessions_one_active', table_name='afk_sessions', postgresql_where=sa.text("status IN ('running','resolved')"))
    op.drop_index(op.f('ix_afk_sessions_user_id'), table_name='afk_sessions')
    op.drop_index('ix_afk_sessions_sweep', table_name='afk_sessions')
    op.drop_index('ix_afk_sessions_character_created', table_name='afk_sessions')
    op.drop_table('afk_sessions')
    op.drop_table('afk_daily_usage')
    # ### end Alembic commands ###
