"""items

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-30 22:26:22.661056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0012'
down_revision: Union[str, Sequence[str], None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affix_definitions',
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('group', sa.String(length=48), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('class_tag', sa.String(length=16), nullable=True),
    sa.Column('tier_min', sa.Integer(), nullable=False),
    sa.Column('tier_max', sa.Integer(), nullable=False),
    sa.Column('rarity_min', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('effect', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rolls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('prefix','suffix')", name=op.f('ck_affix_definitions_kind_valid')),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_affix_definitions_status_valid')),
    sa.CheckConstraint('tier_min BETWEEN 0 AND 10 AND tier_max BETWEEN tier_min AND 10', name=op.f('ck_affix_definitions_tiers_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_affix_definitions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_affix_definitions_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_affix_definitions')),
    sa.UniqueConstraint('code', name=op.f('uq_affix_definitions_code'))
    )
    op.create_index(op.f('ix_affix_definitions_status'), 'affix_definitions', ['status'], unique=False)
    op.create_table('item_sets',
    sa.Column('bonuses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_item_sets_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_item_sets_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_item_sets_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_sets')),
    sa.UniqueConstraint('code', name=op.f('uq_item_sets_code'))
    )
    op.create_index(op.f('ix_item_sets_status'), 'item_sets', ['status'], unique=False)
    op.create_table('item_templates',
    sa.Column('short_description_key', sa.String(length=200), nullable=True),
    sa.Column('lore_key', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('subcategory', sa.String(length=32), nullable=True),
    sa.Column('family', sa.String(length=48), nullable=True),
    sa.Column('slot', sa.String(length=16), nullable=True),
    sa.Column('weapon_family', sa.String(length=96), nullable=True),
    sa.Column('armor_family', sa.String(length=96), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('stack_size', sa.Integer(), nullable=False),
    sa.Column('bind_policy', sa.String(length=16), nullable=False),
    sa.Column('tradeable', sa.Boolean(), nullable=False),
    sa.Column('sellable', sa.Boolean(), nullable=False),
    sa.Column('vendor_value', sa.BigInteger(), nullable=False),
    sa.Column('durability', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sockets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('class_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_classes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocked_classes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_races', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocked_races', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requirement_profile', sa.String(length=32), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('base_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affix_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unique_effect', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('set_code', sa.String(length=96), nullable=True),
    sa.Column('salvage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('icon', sa.String(length=200), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("bind_policy IN ('none','on_pickup','on_equip','account')", name=op.f('ck_item_templates_bind_policy_valid')),
    sa.CheckConstraint("rarity IN ('worn','common','fine','rare','epic','legendary','mythic','relic')", name=op.f('ck_item_templates_rarity_valid')),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_item_templates_status_valid')),
    sa.CheckConstraint('min_level BETWEEN 1 AND 1000', name=op.f('ck_item_templates_min_level_valid')),
    sa.CheckConstraint('stack_size BETWEEN 1 AND 9999', name=op.f('ck_item_templates_stack_size_valid')),
    sa.CheckConstraint('tier BETWEEN 0 AND 10', name=op.f('ck_item_templates_tier_valid')),
    sa.CheckConstraint('vendor_value >= 0', name=op.f('ck_item_templates_vendor_value_valid')),
    sa.ForeignKeyConstraint(['armor_family'], ['armor_families.code'], name=op.f('fk_item_templates_armor_family_armor_families'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_item_templates_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['set_code'], ['item_sets.code'], name=op.f('fk_item_templates_set_code_item_sets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_item_templates_updated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['weapon_family'], ['weapon_families.code'], name=op.f('fk_item_templates_weapon_family_weapon_families'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_templates')),
    sa.UniqueConstraint('code', name=op.f('uq_item_templates_code'))
    )
    op.create_index('ix_item_templates_catalog', 'item_templates', ['category', 'tier', 'rarity'], unique=False)
    op.create_index(op.f('ix_item_templates_status'), 'item_templates', ['status'], unique=False)
    op.create_table('item_instances',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner_character_id', sa.Integer(), nullable=False),
    sa.Column('template_code', sa.String(length=96), nullable=False),
    sa.Column('template_revision_no', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('affixes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('durability', sa.Integer(), nullable=False),
    sa.Column('durability_max', sa.Integer(), nullable=False),
    sa.Column('sockets', sa.Integer(), nullable=False),
    sa.Column('gems', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bound', sa.Boolean(), nullable=False),
    sa.Column('quality', sa.String(length=24), nullable=True),
    sa.Column('upgrade_level', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=16), nullable=False),
    sa.Column('equipped_slot', sa.String(length=16), nullable=True),
    sa.Column('roll_seed', sa.BigInteger(), nullable=False),
    sa.Column('provenance_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('source_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("location IN ('inventory','equipped','bank','mail','market','destroyed')", name=op.f('ck_item_instances_location_valid')),
    sa.CheckConstraint('durability >= 0 AND durability <= durability_max', name=op.f('ck_item_instances_durability_valid')),
    sa.CheckConstraint('quantity >= 1', name=op.f('ck_item_instances_quantity_positive')),
    sa.CheckConstraint('upgrade_level >= 0', name=op.f('ck_item_instances_upgrade_valid')),
    sa.ForeignKeyConstraint(['owner_character_id'], ['characters.id'], name=op.f('fk_item_instances_owner_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_code'], ['item_templates.code'], name=op.f('fk_item_instances_template_code_item_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_instances')),
    sa.UniqueConstraint('provenance_id', name=op.f('uq_item_instances_provenance_id'))
    )
    op.create_index('ix_item_instances_owner_location', 'item_instances', ['owner_character_id', 'location'], unique=False)
    op.create_table('item_provenance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('provenance_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_item_provenance_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_item_provenance_character_id_characters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['item_instances.id'], name=op.f('fk_item_provenance_instance_id_item_instances'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_provenance'))
    )
    op.create_index('ix_item_provenance_instance', 'item_provenance', ['instance_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_item_provenance_provenance_id'), 'item_provenance', ['provenance_id'], unique=False)
    op.create_index('uq_item_provenance_idem', 'item_provenance', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_item_provenance_idem', table_name='item_provenance')
    op.drop_index(op.f('ix_item_provenance_provenance_id'), table_name='item_provenance')
    op.drop_index('ix_item_provenance_instance', table_name='item_provenance')
    op.drop_table('item_provenance')
    op.drop_index('ix_item_instances_owner_location', table_name='item_instances')
    op.drop_table('item_instances')
    op.drop_index(op.f('ix_item_templates_status'), table_name='item_templates')
    op.drop_index('ix_item_templates_catalog', table_name='item_templates')
    op.drop_table('item_templates')
    op.drop_index(op.f('ix_item_sets_status'), table_name='item_sets')
    op.drop_table('item_sets')
    op.drop_index(op.f('ix_affix_definitions_status'), table_name='affix_definitions')
    op.drop_table('affix_definitions')
    # ### end Alembic commands ###
