"""equipment slots

Revision ID: 0013
Revises: 0012
Create Date: 2026-09-30 22:59:02.014774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0013'
down_revision: Union[str, Sequence[str], None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_item_instances_equipped_slot_consistent"),
        "item_instances",
        "(location = 'equipped') = (equipped_slot IS NOT NULL)",
    )
    op.create_index('uq_item_instances_equipped_slot', 'item_instances', ['owner_character_id', 'equipped_slot'], unique=True, postgresql_where=sa.text("location = 'equipped'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_item_instances_equipped_slot_consistent"), "item_instances", type_="check")
    op.drop_index('uq_item_instances_equipped_slot', table_name='item_instances', postgresql_where=sa.text("location = 'equipped'"))
    # ### end Alembic commands ###
