"""professions

Revision ID: 0014
Revises: 0013
Create Date: 2026-09-30 23:18:08.666198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0014'
down_revision: Union[str, Sequence[str], None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professions',
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('tool_kind', sa.String(length=32), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title_key', sa.String(length=200), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_professions_status_valid')),
    sa.CheckConstraint("type IN ('gathering','crafting','service')", name=op.f('ck_professions_type_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_professions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_professions_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professions')),
    sa.UniqueConstraint('code', name=op.f('uq_professions_code'))
    )
    op.create_index(op.f('ix_professions_status'), 'professions', ['status'], unique=False)
    op.create_table('profession_specializations',
    sa.Column('profession_code', sa.String(length=96), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_profession_specializations_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_profession_specializations_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profession_code'], ['professions.code'], name=op.f('fk_profession_specializations_profession_code_professions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_profession_specializations_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profession_specializations')),
    sa.UniqueConstraint('code', name=op.f('uq_profession_specializations_code'))
    )
    op.create_index(op.f('ix_profession_specializations_profession_code'), 'profession_specializations', ['profession_code'], unique=False)
    op.create_index(op.f('ix_profession_specializations_status'), 'profession_specializations', ['status'], unique=False)
    op.create_table('character_profession_meta',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('license_activations', sa.Integer(), nullable=False),
    sa.Column('last_license_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_profession_meta_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk_character_profession_meta'))
    )
    op.create_table('character_professions',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('profession_code', sa.String(length=96), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.BigInteger(), nullable=False),
    sa.Column('specialization_code', sa.String(length=96), nullable=True),
    sa.Column('specialized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('licensed', sa.Boolean(), nullable=False),
    sa.Column('licensed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('level BETWEEN 1 AND 500', name=op.f('ck_character_professions_level_valid')),
    sa.CheckConstraint('specialization_code IS NULL OR level >= 200', name=op.f('ck_character_professions_spec_level')),
    sa.CheckConstraint('xp >= 0', name=op.f('ck_character_professions_xp_valid')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_professions_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profession_code'], ['professions.code'], name=op.f('fk_character_professions_profession_code_professions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['specialization_code'], ['profession_specializations.code'], name=op.f('fk_character_professions_specialization_code_profession_specializations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('character_id', 'profession_code', name=op.f('pk_character_professions'))
    )
    op.create_index('ix_character_professions_licensed', 'character_professions', ['character_id', 'licensed'], unique=False)
    op.create_table('character_titles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('title_code', sa.String(length=96), nullable=False),
    sa.Column('title_key', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_titles_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_titles')),
    sa.UniqueConstraint('character_id', 'title_code', name=op.f('uq_character_titles_character_id_title_code'))
    )
    op.create_index(op.f('ix_character_titles_character_id'), 'character_titles', ['character_id'], unique=False)
    op.create_table('profession_xp_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('profession_code', sa.String(length=96), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('level_before', sa.Integer(), nullable=False),
    sa.Column('level_after', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_profession_xp_events_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profession_code'], ['professions.code'], name=op.f('fk_profession_xp_events_profession_code_professions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profession_xp_events')),
    sa.UniqueConstraint('character_id', 'idempotency_key', name=op.f('uq_profession_xp_events_character_id_idempotency_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profession_xp_events')
    op.drop_index(op.f('ix_character_titles_character_id'), table_name='character_titles')
    op.drop_table('character_titles')
    op.drop_index('ix_character_professions_licensed', table_name='character_professions')
    op.drop_table('character_professions')
    op.drop_table('character_profession_meta')
    op.drop_index(op.f('ix_profession_specializations_status'), table_name='profession_specializations')
    op.drop_index(op.f('ix_profession_specializations_profession_code'), table_name='profession_specializations')
    op.drop_table('profession_specializations')
    op.drop_index(op.f('ix_professions_status'), table_name='professions')
    op.drop_table('professions')
    # ### end Alembic commands ###
