"""crafting

Revision ID: 0015
Revises: 0014
Create Date: 2026-09-30 23:27:30.966045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0015'
down_revision: Union[str, Sequence[str], None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imbue_definitions',
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gold_cost', sa.BigInteger(), nullable=False),
    sa.Column('materials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_imbue_definitions_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_imbue_definitions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_imbue_definitions_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imbue_definitions')),
    sa.UniqueConstraint('code', name=op.f('uq_imbue_definitions_code'))
    )
    op.create_index(op.f('ix_imbue_definitions_status'), 'imbue_definitions', ['status'], unique=False)
    op.create_table('gathering_nodes',
    sa.Column('profession_code', sa.String(length=96), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('actions_per_hour', sa.Float(), nullable=True),
    sa.Column('entries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_gathering_nodes_status_valid')),
    sa.CheckConstraint('tier BETWEEN 0 AND 10', name=op.f('ck_gathering_nodes_tier_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_gathering_nodes_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profession_code'], ['professions.code'], name=op.f('fk_gathering_nodes_profession_code_professions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_gathering_nodes_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gathering_nodes')),
    sa.UniqueConstraint('code', name=op.f('uq_gathering_nodes_code'))
    )
    op.create_index(op.f('ix_gathering_nodes_status'), 'gathering_nodes', ['status'], unique=False)
    op.create_table('recipes',
    sa.Column('profession_code', sa.String(length=96), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('recipe_rarity', sa.String(length=16), nullable=False),
    sa.Column('unlock', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scroll_template_code', sa.String(length=96), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_kind', sa.String(length=32), nullable=True),
    sa.Column('workstation', sa.String(length=32), nullable=True),
    sa.Column('craft_time_s', sa.Float(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_applies', sa.Boolean(), nullable=False),
    sa.Column('fail_chance_pct', sa.Float(), nullable=False),
    sa.Column('fail_return_pct', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("recipe_rarity IN ('common','rare','epic')", name=op.f('ck_recipes_rarity_valid')),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_recipes_status_valid')),
    sa.CheckConstraint('craft_time_s > 0', name=op.f('ck_recipes_time_valid')),
    sa.CheckConstraint('required_level BETWEEN 1 AND 500', name=op.f('ck_recipes_level_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_recipes_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profession_code'], ['professions.code'], name=op.f('fk_recipes_profession_code_professions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scroll_template_code'], ['item_templates.code'], name=op.f('fk_recipes_scroll_template_code_item_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_recipes_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes')),
    sa.UniqueConstraint('code', name=op.f('uq_recipes_code'))
    )
    op.create_index(op.f('ix_recipes_profession_code'), 'recipes', ['profession_code'], unique=False)
    op.create_index(op.f('ix_recipes_status'), 'recipes', ['status'], unique=False)
    op.create_table('character_recipes',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('recipe_code', sa.String(length=96), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('learned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_recipes_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_code'], ['recipes.code'], name=op.f('fk_character_recipes_recipe_code_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'recipe_code', name=op.f('pk_character_recipes'))
    )
    op.create_table('craft_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('recipe_code', sa.String(length=96), nullable=False),
    sa.Column('recipe_revision_no', sa.Integer(), nullable=False),
    sa.Column('recipe_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('consumed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_key', sa.String(length=128), nullable=False),
    sa.Column('claim_key', sa.String(length=128), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running','claimed','cancelled')", name=op.f('ck_craft_jobs_status_valid')),
    sa.CheckConstraint('quantity BETWEEN 1 AND 1000', name=op.f('ck_craft_jobs_quantity_valid')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_craft_jobs_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_code'], ['recipes.code'], name=op.f('fk_craft_jobs_recipe_code_recipes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_craft_jobs')),
    sa.UniqueConstraint('character_id', 'start_key', name=op.f('uq_craft_jobs_character_id_start_key'))
    )
    op.create_index('ix_craft_jobs_character_status', 'craft_jobs', ['character_id', 'status'], unique=False)
    op.create_table('enchant_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_enchant_events_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_id'], ['item_instances.id'], name=op.f('fk_enchant_events_instance_id_item_instances'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enchant_events')),
    sa.UniqueConstraint('character_id', 'idempotency_key', name=op.f('uq_enchant_events_character_id_idempotency_key'))
    )
    op.create_index(op.f('ix_enchant_events_character_id'), 'enchant_events', ['character_id'], unique=False)
    op.add_column('item_instances', sa.Column('enchantments', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_instances', 'enchantments')
    op.drop_index(op.f('ix_enchant_events_character_id'), table_name='enchant_events')
    op.drop_table('enchant_events')
    op.drop_index('ix_craft_jobs_character_status', table_name='craft_jobs')
    op.drop_table('craft_jobs')
    op.drop_table('character_recipes')
    op.drop_index(op.f('ix_recipes_status'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_profession_code'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_gathering_nodes_status'), table_name='gathering_nodes')
    op.drop_table('gathering_nodes')
    op.drop_index(op.f('ix_imbue_definitions_status'), table_name='imbue_definitions')
    op.drop_table('imbue_definitions')
    # ### end Alembic commands ###
