"""market

Revision ID: 0016
Revises: 0015
Create Date: 2026-10-01 03:17:29.001660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0016'
down_revision: Union[str, Sequence[str], None] = '0015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_listings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('seller_character_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('template_code', sa.String(length=96), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.BigInteger(), nullable=False),
    sa.Column('total_price', sa.BigInteger(), nullable=False),
    sa.Column('tax_pct', sa.Float(), nullable=False),
    sa.Column('fee_paid', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('listing_key', sa.String(length=128), nullable=False),
    sa.Column('buyer_character_id', sa.Integer(), nullable=True),
    sa.Column('purchase_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('active','sold','cancelled','expired')", name=op.f('ck_market_listings_status_valid')),
    sa.CheckConstraint('unit_price >= 1 AND total_price >= unit_price AND quantity >= 1', name=op.f('ck_market_listings_price_valid')),
    sa.ForeignKeyConstraint(['buyer_character_id'], ['characters.id'], name=op.f('fk_market_listings_buyer_character_id_characters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['item_instances.id'], name=op.f('fk_market_listings_instance_id_item_instances'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_character_id'], ['characters.id'], name=op.f('fk_market_listings_seller_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_listings')),
    sa.UniqueConstraint('buyer_character_id', 'purchase_key', name=op.f('uq_market_listings_buyer_character_id_purchase_key')),
    sa.UniqueConstraint('seller_character_id', 'listing_key', name=op.f('uq_market_listings_seller_character_id_listing_key'))
    )
    op.create_index('ix_market_listings_active', 'market_listings', ['status', 'template_code', 'unit_price'], unique=False)
    op.create_index('ix_market_listings_expiry', 'market_listings', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_market_listings_seller_character_id'), 'market_listings', ['seller_character_id'], unique=False)
    op.create_index('uq_market_listings_active_instance', 'market_listings', ['instance_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_market_listings_active_instance', table_name='market_listings', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_market_listings_seller_character_id'), table_name='market_listings')
    op.drop_index('ix_market_listings_expiry', table_name='market_listings')
    op.drop_index('ix_market_listings_active', table_name='market_listings')
    op.drop_table('market_listings')
    # ### end Alembic commands ###
