"""party

Revision ID: 0017
Revises: 0016
Create Date: 2026-10-01 03:38:19.228642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0017'
down_revision: Union[str, Sequence[str], None] = '0016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('leader_character_id', sa.Integer(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disbanded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['leader_character_id'], ['characters.id'], name=op.f('fk_parties_leader_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parties'))
    )
    op.create_table('party_invites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','accepted','declined','expired','cancelled')", name=op.f('ck_party_invites_status_valid')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_party_invites_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['characters.id'], name=op.f('fk_party_invites_invited_by_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_party_invites_party_id_parties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_party_invites'))
    )
    op.create_index(op.f('ix_party_invites_character_id'), 'party_invites', ['character_id'], unique=False)
    op.create_index('uq_party_invites_pending', 'party_invites', ['party_id', 'character_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('party_members',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('tank','healer','support','dps')", name=op.f('ck_party_members_role_valid')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_party_members_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_party_members_party_id_parties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_party_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk_party_members'))
    )
    op.create_index('ix_party_members_party', 'party_members', ['party_id'], unique=False)
    op.create_table('party_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('client_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_party_messages_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_party_messages_party_id_parties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_party_messages')),
    sa.UniqueConstraint('character_id', 'client_key', name=op.f('uq_party_messages_character_id_client_key'))
    )
    op.create_index('ix_party_messages_party', 'party_messages', ['party_id', 'id'], unique=False)
    op.add_column('afk_sessions', sa.Column('group_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_afk_sessions_group_id'), 'afk_sessions', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_afk_sessions_group_id'), table_name='afk_sessions')
    op.drop_column('afk_sessions', 'group_id')
    op.drop_index('ix_party_messages_party', table_name='party_messages')
    op.drop_table('party_messages')
    op.drop_index('ix_party_members_party', table_name='party_members')
    op.drop_table('party_members')
    op.drop_index('uq_party_invites_pending', table_name='party_invites', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_party_invites_character_id'), table_name='party_invites')
    op.drop_table('party_invites')
    op.drop_table('parties')
    # ### end Alembic commands ###
