"""goals

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-01 03:50:22.298555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0018'
down_revision: Union[str, Sequence[str], None] = '0017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('counter', sa.String(length=48), nullable=False),
    sa.Column('threshold', sa.BigInteger(), nullable=False),
    sa.Column('status_rarity', sa.String(length=16), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('title_code', sa.String(length=96), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_achievements_status_valid')),
    sa.CheckConstraint("status_rarity IN ('bronze','silver','gold','platinum','mythic','relic')", name=op.f('ck_achievements_rarity_valid')),
    sa.CheckConstraint('threshold >= 1', name=op.f('ck_achievements_threshold_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_achievements_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_achievements_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements')),
    sa.UniqueConstraint('code', name=op.f('uq_achievements_code'))
    )
    op.create_index(op.f('ix_achievements_counter'), 'achievements', ['counter'], unique=False)
    op.create_index(op.f('ix_achievements_status'), 'achievements', ['status'], unique=False)
    op.create_table('quests',
    sa.Column('quest_type', sa.String(length=16), nullable=False),
    sa.Column('chain', sa.String(length=48), nullable=True),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('class_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('repeatable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('description_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("quest_type IN ('kill','collect','profession','explore','boss','promotion','tutorial')", name=op.f('ck_quests_type_valid')),
    sa.CheckConstraint("status IN ('draft','published','disabled','archived')", name=op.f('ck_quests_status_valid')),
    sa.CheckConstraint('min_level BETWEEN 1 AND 1000', name=op.f('ck_quests_level_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_quests_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_quests_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quests')),
    sa.UniqueConstraint('code', name=op.f('uq_quests_code'))
    )
    op.create_index(op.f('ix_quests_quest_type'), 'quests', ['quest_type'], unique=False)
    op.create_index(op.f('ix_quests_status'), 'quests', ['status'], unique=False)
    op.create_table('character_achievements',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('achievement_code', sa.String(length=96), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_code'], ['achievements.code'], name=op.f('fk_character_achievements_achievement_code_achievements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_achievements_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'achievement_code', name=op.f('pk_character_achievements'))
    )
    op.create_table('character_counters',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('counter', sa.String(length=48), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value >= 0', name=op.f('ck_character_counters_value_non_negative')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_counters_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'counter', name=op.f('pk_character_counters'))
    )
    op.create_table('character_quests',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('quest_code', sa.String(length=96), nullable=False),
    sa.Column('quest_revision_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_key', sa.String(length=128), nullable=True),
    sa.Column('times_completed', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('active','completed','claimed','abandoned')", name=op.f('ck_character_quests_status_valid')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_quests_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_code'], ['quests.code'], name=op.f('fk_character_quests_quest_code_quests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'quest_code', name=op.f('pk_character_quests'))
    )
    op.create_index('ix_character_quests_character_status', 'character_quests', ['character_id', 'status'], unique=False)
    op.create_table('character_title_selection',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('title_ref', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_title_selection_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk_character_title_selection'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_title_selection')
    op.drop_index('ix_character_quests_character_status', table_name='character_quests')
    op.drop_table('character_quests')
    op.drop_table('character_counters')
    op.drop_table('character_achievements')
    op.drop_index(op.f('ix_quests_status'), table_name='quests')
    op.drop_index(op.f('ix_quests_quest_type'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_achievements_status'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_counter'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
