"""content_reviews

Revision ID: 0019
Revises: 0018
Create Date: 2026-10-01 04:29:41.441306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0019'
down_revision: Union[str, Sequence[str], None] = '0018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('base_revision_no', sa.Integer(), nullable=False),
    sa.Column('edit_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('requested','approved','changes_requested')", name=op.f('ck_content_reviews_status_valid')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_content_reviews_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_content_reviews_reviewed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_reviews')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'base_revision_no', 'edit_version', name=op.f('uq_content_reviews_entity_type_entity_id_base_revision_no_edit_version'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_reviews')
    # ### end Alembic commands ###
